#!/usr/bin/env Rscript

options(error = function() { traceback(3); q(status=1) })

library(readr)
library(stringr)
library(tibble)

OUTPUT_FILE <- "roxygen.csv"
HEADER <- "# Generated by roxygen2: do not edit by hand"

args <- commandArgs(trailingOnly=TRUE)
if (length(args) != 1) {
  stop("Missing a path to the package source")
}

package_path <- args[1]
namespace_file <- file.path(package_path, "NAMESPACE")
uses_roxygen <- FALSE

if (file.exists(namespace_file)) {
  lines <- readLines(namespace_file)
  uses_roxygen <- any(str_detect(lines, fixed(HEADER)))
}

df <- tibble(uses_roxygen)
write_csv(df, OUTPUT_FILE)
